export const PROJECT_DATA_REQUEST='PROJECT_DATA_REQUEST';
export const PROJECT_DATA_SUCCESS='PROJECT_DATA_SUCCESS';
export const PROJECT_DATA_FAILURE='PROJECT_DATA_FAILURE';

export const ADD_PROJECT_SUCCESS='ADD_PROJECT_SUCCESS';
export const DELETE_PROJECT_SUCCESS='DELETE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_SUCCESS='UPDATE_PROJECT_SUCCESS';
